// `pnpm gen`: regenerate src/types.ts from the pipeline's JSON Schema.
//
// The schema is written by `fd export-schema` from the Pydantic model in
// export/site.py, so the site's types cannot drift from the file it reads: a field that
// moves in Python is a type error here on the next run rather than `undefined` at runtime.
// The API is used rather than the `json2ts` CLI for one reason — the CLI names the root
// type after the schema's title ("Flight Detective dashboard data (schema_version 1)"),
// and `compile(schema, name)` lets it be `DashboardData`.
import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { compile } from "json-schema-to-typescript";

const here = fileURLToPath(new URL("..", import.meta.url));
const SCHEMA = resolve(here, "../specs/dashboard-data.schema.json");
const OUT = resolve(here, "src/types.ts");

const schema = JSON.parse(await readFile(SCHEMA, "utf8"));

// Pydantic titles every property ("Schema Version", "Code", "Date"…), and the generator
// turns each one into a named alias — `export type Date = string` shadowing the global
// among them. Only the $defs titles are wanted, since those name the interfaces, so drop
// the property-level ones. The root title goes too: with it present the root interface is
// named after it rather than after the `name` argument below.
// `$id` would name it too, and is only there to identify the schema, not to resolve a
// reference: every `$ref` in the file is a local `#/$defs/...` pointer.
delete schema.title;
delete schema.$id;
for (const def of [schema, ...Object.values(schema.$defs ?? {})]) {
  for (const property of Object.values(def.properties ?? {})) delete property.title;
}

const ts = await compile(schema, "DashboardData", {
  additionalProperties: false,
  bannerComment: [
    "/* eslint-disable */",
    "/**",
    " * Generated by `pnpm gen` from specs/dashboard-data.schema.json. Do not edit by hand;",
    " * regenerate the schema with `fd export-schema` and re-run `pnpm gen`.",
    " */",
  ].join("\n"),
});
await writeFile(OUT, ts);
console.log(`wrote ${OUT}`);
