/* eslint-disable */
/**
 * Generated by `pnpm gen` from specs/dashboard-data.schema.json. Do not edit by hand;
 * regenerate the schema with `fd export-schema` and re-run `pnpm gen`.
 */

export interface DashboardData {
  schema_version: number;
  generated_at: string;
  /**
   * Latest day the fares were observed; null before the first ingest
   */
  observed_on: string | null;
  carriers: Carrier[];
  destinations: DestinationInfo[];
  horizons: number[];
  series: CarrierSeries[];
  bands: Band[];
  events: Event[];
  news_status: NewsStatus;
  arbitrage: Arbitrage | null;
  efficiency: Efficiency[];
  seasonal_gauge: SeasonalGauge | null;
}
/**
 * One line on the chart, one chip in the filter bar, one dot in the scatter.
 */
export interface Carrier {
  code: string;
  name: string;
  /**
   * `--carrier-<code>` from specs/ux/design-system.md § Tokens
   */
  color: string;
  /**
   * Transit airport, or null when the carrier flies direct
   */
  hub: string | null;
  direct: boolean;
  /**
   * Reference door-to-door time, for the hover card before a fare is loaded
   */
  typical_transit_minutes: number;
}
export interface DestinationInfo {
  code: string;
  label: string;
}
/**
 * The lowest fare per departure date for one (destination, horizon, carrier).
 */
export interface CarrierSeries {
  destination: string;
  horizon_days: number;
  carrier: string;
  points: SeriesPoint[];
}
export interface SeriesPoint {
  departure_date: string;
  price_eur: number;
}
/**
 * One edition of a calendar window, clipped to the export window.
 */
export interface Band {
  tag: string;
  label: string;
  short_label: string;
  kind: "wedding" | "religious" | "french";
  from: string;
  to: string;
  multiplier_low: number;
  multiplier_high: number;
}
/**
 * One `news_event` row as the feed, the drawer and the chart pins need it.
 */
export interface Event {
  date: string;
  severity: "high" | "med" | "low";
  headline: string;
  /**
   * Publisher host, for the feed's `date · source` line
   */
  source: string;
  source_url: string;
  /**
   * The ingest's own note on the row: how many outlets carried it and which keyword set the severity. v1 has no estimate of the fare impact itself.
   */
  impact_text: string | null;
  /**
   * Always null in v1: GDELT's DOC 2.0 artlist carries titles and URLs, not article text.
   */
  body: string | null;
}
/**
 * Whether the news half of the pipeline is still working, regardless of what it found.
 *
 * A week in which nothing happened and a week in which every query failed both export an
 * empty `events` list, and the run log is the only thing that tells them apart — so the
 * feed reads its health from here rather than from its own row count.
 */
export interface NewsStatus {
  /**
   * Europe/Paris day of the newest news run whose queries answered; null before the news step has ever succeeded
   */
  last_success: string | null;
  /**
   * One line naming why the newest failing news run failed; null if none has ever failed. Exported even when a later run recovered — the page shows it only beside a stale last_success, and dropping it here would lose the reason.
   */
  last_error: string | null;
}
/**
 * Lahore against Sialkot on one departure date, with the ground transfer priced in.
 */
export interface Arbitrage {
  departure_date: string;
  lhe_eur: number;
  skt_eur: number;
  isb_eur: number | null;
  /**
   * `lhe_eur - skt_eur`, as analytics defines it: positive means Sialkot is the cheaper airport. The design's card captions this the other way round.
   */
  spread_eur: number;
  ground_transfer_eur: number;
  ground_time: string;
  verdict: "lhe" | "skt" | "either";
}
/**
 * One dot of the price-against-transit-time scatter.
 */
export interface Efficiency {
  carrier: string;
  price_eur: number;
  transit_minutes: number;
}
export interface SeasonalGauge {
  current_avg_eur: number;
  baseline_avg_eur: number;
  pct: number;
  method: string;
}
