import js from "@eslint/js";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // src/types.ts is generated by `pnpm gen`; dist/ is build output. Neither is hand-written.
  { ignores: ["dist", "src/types.ts", "node_modules"] },
  js.configs.recommended,
  {
    // The type-checked rules only apply where there is a type to check: eslint.config.js and
    // scripts/*.mjs are outside tsconfig's `include`, and asking for type information there
    // is an error rather than a skipped rule.
    files: ["**/*.{ts,tsx}"],
    extends: [tseslint.configs.recommendedTypeChecked, reactHooks.configs.flat["recommended-latest"]],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
    plugins: { "react-refresh": reactRefresh },
    rules: {
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
    },
  },
  {
    files: ["vite.config.ts", "vitest.setup.ts", "**/*.{js,mjs}"],
    languageOptions: { globals: globals.node },
  },
);
